#!/bin/bash
# protect-docs.sh — PreToolUse on Edit|Write. STATE.md is generated, ORDERS.md
# is the design seat's, CLAUDE.md changes are a ruling. The desk touches none.
# The owner and the design seat mark their checkout with an empty
# .claude/OWNER_SEAT file (gitignored, never copied into worktrees) and the
# guard stands down there.
INPUT=$(cat); . "$(dirname "$0")/_json.sh"
CWD=$(json_field "$INPUT" cwd); [ -n "$CWD" ] && cd "$CWD" 2>/dev/null
[ -f .claude/OWNER_SEAT ] && exit 0
F=$(json_field "$INPUT" tool_input.file_path)
F=$(printf '%s' "$F" | sed -e 's#\\#/#g' -e 's#//*#/#g')
case "$F" in
  */Docs/STATE.md)  echo "Blocked: Docs/STATE.md is generated by Scripts/status.py. Fix the generator or the thing it measures." >&2; exit 2 ;;
  */Docs/ORDERS.md) echo "Blocked: Docs/ORDERS.md is written by the design seat. Disagree in .claude/DESK.md." >&2; exit 2 ;;
  */CLAUDE.md)      echo "Blocked: CLAUDE.md edits are an owner ruling. Propose the line in .claude/DESK.md." >&2; exit 2 ;;
esac
exit 0
