#!/bin/bash
# protect-docs.sh — PreToolUse on Edit|Write. STATE.md is generated, ORDERS.md
# is the design seat's, CLAUDE.md changes are a ruling. Lanes touch none.
INPUT=$(cat); . "$(dirname "$0")/_json.sh"
F=$(json_field "$INPUT" tool_input.file_path)
F="${F//\\//}"
case "$F" in
  */Docs/STATE.md)  echo "Blocked: Docs/STATE.md is generated by Scripts/status.py. Fix the generator or the thing it measures." >&2; exit 2 ;;
  */Docs/ORDERS.md) echo "Blocked: Docs/ORDERS.md is written by the design seat. Disagree in Docs/reports/<LANE>.md." >&2; exit 2 ;;
  */CLAUDE.md)      echo "Blocked: CLAUDE.md edits are an owner ruling. Propose the line in your report." >&2; exit 2 ;;
esac
exit 0
