#pragma once

#include "CoreMinimal.h"
#include "Weapons/BreakerWeaponArchetype.h"

// ---------------------------------------------------------------------------
// The placeholder sounds, SYNTHESIZED. Pure, header-inline, no world,
// no assets: every sample is a deterministic function of its index, which is
// what lets the automation suite prove the only things about a sound a test
// can prove — that it renders the length it claims, that no sample clips,
// that it starts and ends at silence (a waveform that begins off zero is an
// audible click), and that two renders are identical.
//
// WHY SYNTHESIS AND NOT A FILE. The project has no audio assets and the
// licensing of anything downloaded is the owner's problem and has to be
// visible. A sound generated by arithmetic in this header has no licence at
// all — the provenance IS the code. When real sounds arrive they replace the
// waves the director queues, and this header keeps rendering the fallback.
//
// Every figure below is O2 PLACEHOLDER: durations, frequencies, decay rates
// and gains are readability guesses that no playtest has confirmed.
// ---------------------------------------------------------------------------
namespace BreakerSound
{
    inline float EffectsGain(float Master, float Effects)
    {
        return FMath::Clamp(Master, 0.0f, 1.0f) * FMath::Clamp(Effects, 0.0f, 1.0f);
    }
    // 32 kHz mono: placeholder transients have no content above 10 kHz worth
    // keeping, and a smaller buffer is a cheaper queue. O2 PLACEHOLDER
    constexpr int32 SampleRate = 32000;

    constexpr float FireDurationSeconds = 0.14f;   // O2 PLACEHOLDER
    constexpr float HitDurationSeconds  = 0.06f;   // O2 PLACEHOLDER
    constexpr float KillDurationSeconds = 0.30f;   // O2 PLACEHOLDER
    constexpr float TakeHitDurationSeconds = 0.22f; // O2 PLACEHOLDER
    constexpr float AbilityCastDurationSeconds = 0.20f; // O2 PLACEHOLDER
    // The player's own death (O193): one low sound at the hard cut. Short,
    // because it lands at the instant the screen goes black and the black
    // itself is the weight; the ring-out is the sine's slow decay, not length.
    constexpr float PlayerDeathDurationSeconds = 0.4f; // O2 PLACEHOLDER
    constexpr float EntropyActivationDurationSeconds = 0.32f; // O2 PLACEHOLDER
    constexpr float EntropyActivationMinGapSeconds = 0.15f; // O2 PLACEHOLDER: one crowd cue, not a chorus.

    inline int32 SampleCount(float DurationSeconds)
    {
        return FMath::Max(0, FMath::RoundToInt(DurationSeconds * SampleRate));
    }

    // Deterministic white noise: an integer hash of the sample index mapped to
    // [-1, 1]. NOT FMath::Rand — a seeded stream the caller cannot replay
    // would make the render nondeterministic and the determinism test above
    // is the whole point of doing this in a header.
    inline float NoiseAt(uint32 Index)
    {
        uint32 H = Index * 747796405u + 2891336453u;
        H = ((H >> ((H >> 28u) + 4u)) ^ H) * 277803737u;
        H = (H >> 22u) ^ H;
        return static_cast<float>(H) * (2.0f / 4294967295.0f) - 1.0f;
    }

    // Shared shape: a 2 ms attack ramp in and a hard fade over the final 10 ms
    // out, so no waveform ever starts or stops off zero. The decay between
    // them belongs to each sound.
    inline float Envelope(float T, float DurationSeconds, float DecayRate)
    {
        if (T < 0.0f || T >= DurationSeconds) return 0.0f;
        const float Attack = FMath::Min(T / 0.002f, 1.0f);
        const float Remaining = DurationSeconds - T;
        // THE RELEASE HAS TO REACH ZERO AT THE LAST SAMPLE, not at the
        // duration. The last rendered index sits one sample SHORT of the
        // duration, so a fade that only arrives at the duration leaves a small
        // nonzero value there — and for a loud enough cue that value quantizes
        // to 1 rather than 0, which is a click on every shot. Found by
        // measurement: the Machinegun's voice was the first one loud enough at
        // that instant for it to show.
        constexpr float LastSample = 1.0f / SampleRate;
        if (Remaining <= LastSample) return 0.0f;
        const float Release = FMath::Min(Remaining / 0.010f, 1.0f);
        return Attack * Release * FMath::Exp(-T * DecayRate);
    }

    // WEAPON FIRE: a noise burst over a falling body tone — the crack and the
    // thump of a report, in that order of weight. Gain 0.5 leaves headroom
    // for the hit and kill sounds to land on top of sustained fire.
    // ---- A GUN THAT SOUNDS LIKE ITSELF ----------------------------------
    // Owner: "my gun sounds like a nerf gun", and "i dont know what weapon is
    // in my hand". Both are the same finding from two directions: every one of
    // the eight archetypes played the IDENTICAL burst above. The per-archetype
    // route already existed in ABreakerSoundDirector - it just resolved to an
    // authored .wav per archetype, none is authored, and so all eight fell
    // back to the one shared render.
    //
    // TWO NOISE COLOURS, BOTH MEMORYLESS. A real report is a bright crack over
    // a dark thump, and a one-pole filter cannot be used here: every sample has
    // to be a pure function of its index or the determinism test that makes
    // this whole header defensible stops holding. So the colour comes from the
    // hash's own rate instead.
    //
    //   BrightNoise is a first DIFFERENCE of the noise, which is a 6 dB/octave
    //   high-pass: the snap of the round leaving the barrel.
    //   DarkNoise samples the hash a quarter as often and interpolates between,
    //   which is noise two octaves down: the body of the blast and the room.
    //
    // Nothing here is mastered and nothing here is final. Every figure is O2
    // PLACEHOLDER; what is authored is the SHAPE of the differences, which is
    // the part a player hears as "that is the shotgun".
    inline float BrightNoise(uint32 Index)
    {
        return 0.5f * (NoiseAt(Index) - NoiseAt(Index - 1));
    }

    inline float DarkNoise(uint32 Index)
    {
        const uint32 Coarse = Index / 4;
        const float Blend = static_cast<float>(Index % 4) * 0.25f;
        return FMath::Lerp(NoiseAt(Coarse), NoiseAt(Coarse + 1), Blend);
    }

    // What separates one gun from another, as numbers rather than as eight
    // hand-written functions: eight bespoke renders would drift the moment one
    // was retuned, and nothing could assert that they still differed.
    struct FFireVoice
    {
        float DurationSeconds = FireDurationSeconds;
        // The snap. A high decay is a crack; a low one is a roar.
        float CrackDecay = 55.0f;
        float CrackGain = 0.65f;
        // The thump under it, and how far it falls while it sounds.
        float BodyStartHz = 160.0f;
        float BodyFallHz = 400.0f;
        float BodyDecay = 30.0f;
        float BodyGain = 0.35f;
        // The room answering: dark noise on its own slow decay. This is what
        // makes a big gun sound big and a small one sound close.
        float TailDecay = 22.0f;
        float TailGain = 0.0f;
        float Gain = 0.5f;
    };

    // THE EIGHT VOICES. Read them as a set rather than one at a time: what is
    // authored is that a Sidearm is short and bright, a Sniper is a hard crack
    // with a long tail, a Shotgun is mostly body, a Rocket is nearly all tail,
    // and the three rifles differ from each other by far less than any of them
    // differs from those. All O2 PLACEHOLDER.
    inline FFireVoice FireVoiceFor(EBreakerWeaponArchetype Archetype)
    {
        FFireVoice Voice;
        switch (Archetype)
        {
        case EBreakerWeaponArchetype::SMG:
            // Fast and small: almost no body, and short enough that sustained
            // fire reads as a rattle rather than as overlapping reports.
            Voice.DurationSeconds = 0.09f;
            Voice.CrackDecay = 80.0f; Voice.CrackGain = 0.78f;
            Voice.BodyStartHz = 210.0f; Voice.BodyFallHz = 520.0f;
            Voice.BodyDecay = 46.0f;    Voice.BodyGain = 0.22f;
            Voice.TailGain = 0.06f;     Voice.Gain = 0.42f;
            break;
        case EBreakerWeaponArchetype::Sidearm:
            // The smallest thing in the game, and it should sound like it:
            // brightest crack, least body, shortest of all.
            Voice.DurationSeconds = 0.08f;
            Voice.CrackDecay = 95.0f; Voice.CrackGain = 0.82f;
            Voice.BodyStartHz = 240.0f; Voice.BodyFallHz = 600.0f;
            Voice.BodyDecay = 55.0f;    Voice.BodyGain = 0.18f;
            Voice.TailGain = 0.04f;     Voice.Gain = 0.40f;
            break;
        case EBreakerWeaponArchetype::Sniper:
            // A hard crack and a LONG tail: the shot is over instantly and the
            // room is not. This is the one archetype whose sound should still
            // be going after the player has stopped looking at what they hit.
            Voice.DurationSeconds = 0.42f;
            Voice.CrackDecay = 42.0f; Voice.CrackGain = 0.70f;
            Voice.BodyStartHz = 120.0f; Voice.BodyFallHz = 220.0f;
            Voice.BodyDecay = 16.0f;    Voice.BodyGain = 0.36f;
            Voice.TailDecay = 7.0f;     Voice.TailGain = 0.30f;
            Voice.Gain = 0.62f;
            break;
        case EBreakerWeaponArchetype::Shotgun:
            // Mostly body. The crack is there and it is not the point; a
            // shotgun is a low, wide shove of air.
            Voice.DurationSeconds = 0.30f;
            Voice.CrackDecay = 26.0f; Voice.CrackGain = 0.40f;
            Voice.BodyStartHz = 95.0f;  Voice.BodyFallHz = 150.0f;
            Voice.BodyDecay = 12.0f;    Voice.BodyGain = 0.60f;
            Voice.TailDecay = 11.0f;    Voice.TailGain = 0.26f;
            Voice.Gain = 0.66f;
            break;
        case EBreakerWeaponArchetype::Rocket:
            // Nearly all tail and almost no crack: a launch is a rush, not a
            // report, and it must not be mistakable for any of the guns.
            Voice.DurationSeconds = 0.55f;
            Voice.CrackDecay = 9.0f;  Voice.CrackGain = 0.22f;
            Voice.BodyStartHz = 78.0f;  Voice.BodyFallHz = 90.0f;
            Voice.BodyDecay = 7.0f;     Voice.BodyGain = 0.42f;
            Voice.TailDecay = 4.0f;     Voice.TailGain = 0.46f;
            Voice.Gain = 0.70f;
            break;
        case EBreakerWeaponArchetype::Machinegun:
            // Heavier than the rifle and slower to die, so a held trigger
            // reads as weight rather than as speed.
            Voice.DurationSeconds = 0.17f;
            Voice.CrackDecay = 44.0f; Voice.CrackGain = 0.60f;
            Voice.BodyStartHz = 130.0f; Voice.BodyFallHz = 300.0f;
            Voice.BodyDecay = 22.0f;    Voice.BodyGain = 0.44f;
            Voice.TailDecay = 15.0f;    Voice.TailGain = 0.16f;
            Voice.Gain = 0.58f;
            break;
        case EBreakerWeaponArchetype::BurstRifle:
            // The rifle, tightened. Three of these land inside a third of a
            // second, so it has to be the shortest of the three rifles or the
            // burst smears into one noise.
            Voice.DurationSeconds = 0.11f;
            Voice.CrackDecay = 66.0f; Voice.CrackGain = 0.70f;
            Voice.BodyStartHz = 175.0f; Voice.BodyFallHz = 440.0f;
            Voice.BodyDecay = 36.0f;    Voice.BodyGain = 0.30f;
            Voice.TailGain = 0.08f;     Voice.Gain = 0.48f;
            break;
        default:
            // RIFLE, and it keeps the shipped numbers exactly. It is the gun
            // the owner has spent every playtest holding, so it is the one that
            // must not move underneath him in the same pass that gives the
            // other seven a voice. The tail is the only addition.
            Voice.TailDecay = 18.0f; Voice.TailGain = 0.12f;
            break;
        }
        return Voice;
    }

    inline float WeaponFireSample(int32 Index, const FFireVoice& Voice)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const uint32 Sample = static_cast<uint32>(Index);
        const float Crack = BrightNoise(Sample) * Envelope(T, Voice.DurationSeconds, Voice.CrackDecay);
        const float BodyHz = Voice.BodyStartHz - Voice.BodyFallHz * T;
        const float Body = FMath::Sin(2.0f * PI * BodyHz * T)
            * Envelope(T, Voice.DurationSeconds, Voice.BodyDecay);
        const float Tail = DarkNoise(Sample ^ 0x9E37u) * Envelope(T, Voice.DurationSeconds, Voice.TailDecay);
        // NORMALISED BY THE MIX, so raising one part cannot quietly raise the
        // whole sound past clipping. Gain above is then the only dial that
        // decides how loud this gun is against the others.
        const float Mix = Voice.CrackGain + Voice.BodyGain + Voice.TailGain;
        const float Blend = Mix > KINDA_SMALL_NUMBER
            ? (Voice.CrackGain * Crack + Voice.BodyGain * Body + Voice.TailGain * Tail) / Mix : 0.0f;
        return Voice.Gain * Blend;
    }

    // The shared fallback, kept so a caller with no archetype in hand still
    // has a sound. It is the RIFLE, not a ninth voice: a default that is
    // nothing in particular is how a weapon ends up sounding like neither
    // itself nor anything else.
    inline float WeaponFireSample(int32 Index)
    {
        return WeaponFireSample(Index, FireVoiceFor(EBreakerWeaponArchetype::Rifle));
    }


    // HIT CONFIRM: a short bright tick, pitched well above the fire sound so
    // it reads THROUGH sustained fire rather than under it.
    inline float HitConfirmSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 1400.0f - 8000.0f * T;   // falls 1400 -> ~920 over 60 ms
        return 0.35f * FMath::Sin(2.0f * PI * Hz * T) * Envelope(T, HitDurationSeconds, 60.0f);
    }

    // KILL: a low two-tone drop, longer and heavier than either of the others
    // — the one event of the three that deserves weight.
    inline float KillSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 220.0f - 500.0f * T;   // falls 220 -> 70 over 300 ms
        const float Fundamental = FMath::Sin(2.0f * PI * Hz * T);
        const float Fifth = 0.4f * FMath::Sin(2.0f * PI * Hz * 1.5f * T);
        return 0.55f * (Fundamental + Fifth) / 1.4f * Envelope(T, KillDurationSeconds, 9.0f);
    }

    // Renders one whole sound as the 16-bit mono PCM the procedural wave
    // queues. The float sample is clamped before quantization so an authored
    // gain above 1 can distort but can never wrap.
    template <typename SampleFn>
    inline void RenderPcm16(TArray<int16>& Out, float DurationSeconds, SampleFn Sample)
    {
        const int32 Count = SampleCount(DurationSeconds);
        Out.SetNumUninitialized(Count);
        for (int32 Index = 0; Index < Count; ++Index)
        {
            const float Clamped = FMath::Clamp(Sample(Index), -1.0f, 1.0f);
            Out[Index] = static_cast<int16>(FMath::RoundToInt(Clamped * 32767.0f));
        }
    }

    // TAKE-HIT: a dull mid thud, pitched between the hit confirm and the
    // kill so incoming and outgoing never read as the same voice.
    inline float TakeHitSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 180.0f - 400.0f * T;   // falls 180 -> ~92 over 220 ms
        const float Body = FMath::Sin(2.0f * PI * Hz * T);
        const float Grit = 0.25f * NoiseAt(static_cast<uint32>(Index) ^ 0x5A5Au);
        return 0.45f * (Body + Grit) / 1.25f * Envelope(T, TakeHitDurationSeconds, 14.0f);
    }

    // ABILITY CAST: the fifth verb, and the only sound in the set that RISES.
    // Every other verb falls — fire, hit, kill and take-hit all sweep downward
    // — so DIRECTION alone separates an ability from anything the weapon does,
    // before pitch or timbre are considered. That matters more than usual
    // here: this one cue plays for every ability that has no override of its
    // own, so it has to read as "an ability happened" against four sounds the
    // player hears constantly.
    inline float AbilityCastSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 320.0f + 2600.0f * T;   // rises 320 -> 840 over 200 ms
        const float Fundamental = FMath::Sin(2.0f * PI * Hz * T);
        // An octave above at a third the weight: shimmer, so the sweep reads
        // as charged rather than as a test tone.
        const float Octave = 0.33f * FMath::Sin(2.0f * PI * Hz * 2.0f * T);
        return 0.40f * (Fundamental + Octave) / 1.33f * Envelope(T, AbilityCastDurationSeconds, 5.0f);
    }

    // PLAYER DEATH: the sixth verb (O193, "one low sound"). One sine and
    // nothing else — no noise, no fifth, no octave — gliding from 110 Hz to
    // 55 Hz across the whole duration under a slow decay. EVERY PARTIAL SITS
    // BELOW 200 HZ, which is what separates it from the take-hit thud directly
    // above it (180 Hz with grit) and from anything the weapon does: the cue
    // is felt more than heard, and it plays at the cut to black where nothing
    // else is happening.
    //
    // The glide is integrated rather than written as Sin(2π·Hz(T)·T): the
    // instantaneous frequency of that shortcut is Hz(T) + T·Hz'(T), which for a
    // fall this long would hit zero before the end. Phase = 2π(F0·T + (F1-F0)·T²/2D)
    // has instantaneous frequency F0 + (F1-F0)·T/D, exactly the line described.
    inline float PlayerDeathSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        constexpr float StartHz = 110.0f;   // O2 PLACEHOLDER
        constexpr float EndHz = 55.0f;      // O2 PLACEHOLDER
        const float Phase = 2.0f * PI * (StartHz * T + (EndHz - StartHz) * T * T / (2.0f * PlayerDeathDurationSeconds));
        // Decay 4: roughly -7 dB across the 0.4 s, a ring-out rather than a hit.
        return 0.6f * FMath::Sin(Phase) * Envelope(T, PlayerDeathDurationSeconds, 4.0f);   // O2 PLACEHOLDER
    }

    // WeaponFireSample is overloaded now, so its address is ambiguous: the
    // lambda names which one. A cast would have worked and would have been the
    // wrong answer - it silently picks an overload where this states it.
    inline void RenderWeaponFire(TArray<int16>& Out)
    {
        RenderPcm16(Out, FireDurationSeconds, [](int32 Index) { return WeaponFireSample(Index); });
    }

    // One archetype's own report. The duration comes from the voice, so a
    // Sniper renders four times the buffer a Sidearm does and neither is
    // padded with silence it has to queue.
    inline void RenderArchetypeFire(TArray<int16>& Out, EBreakerWeaponArchetype Archetype)
    {
        const FFireVoice Voice = FireVoiceFor(Archetype);
        RenderPcm16(Out, Voice.DurationSeconds,
            [&Voice](int32 Index) { return WeaponFireSample(Index, Voice); });
    }
    // A brief dry crack followed by a falling, rough tail: the start of decay.
    inline float EntropyActivationSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Phase = 2 * PI * (440.0f * T - 500.0f * T * T); // O2 PLACEHOLDER
        const float Grit = NoiseAt(static_cast<uint32>(Index) ^ 0xE170u);
        return .42f * (.6f * FMath::Sin(Phase) + .4f * Grit) * Envelope(T, EntropyActivationDurationSeconds, 9.0f); // O2 PLACEHOLDER
    }
    // O2: a restrained rising mark, followed later by a short low erasure snap.
    inline float VoidActivationSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .3f * FMath::Sin(2 * PI * (210 * T + 700 * T * T)) * Envelope(T, .24f, 8);
    }
    inline float VoidBurstSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .4f * (.7f * FMath::Sin(2 * PI * 90 * T) + .3f * NoiseAt(Index ^ 0xE2A5u)) * Envelope(T, .18f, 14);
    }
    inline float RiftActivationSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .35f * (.7f * FMath::Sin(2 * PI * (760 * T - 900 * T * T))
            + .3f * NoiseAt(Index ^ 0x21F7u)) * Envelope(T, .22f, 12); // O2 displacement snap.
    }
    // O2 reaction signatures: low collapse, rough wither, high tearing snap.
    inline float ReactionCollapseSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .4f * FMath::Sin(2 * PI * (170 * T - 150 * T * T)) * Envelope(T, .28f, 12);
    }
    inline float ReactionWitherSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .3f * NoiseAt(Index ^ 0x7174u) * Envelope(T, .3f, 10);
    }
    inline float ReactionTearSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        return .35f * (.7f * FMath::Sin(2 * PI * (900 * T - 1300 * T * T))
            + .3f * NoiseAt(Index ^ 0x7EA2u)) * Envelope(T, .2f, 14);
    }
    inline void RenderReactionCollapse(TArray<int16>& Out) { RenderPcm16(Out, .28f, &ReactionCollapseSample); }
    inline void RenderReactionWither(TArray<int16>& Out) { RenderPcm16(Out, .3f, &ReactionWitherSample); }
    inline void RenderReactionTear(TArray<int16>& Out) { RenderPcm16(Out, .2f, &ReactionTearSample); }
    inline void RenderRiftActivation(TArray<int16>& Out) { RenderPcm16(Out, .22f, &RiftActivationSample); }
    inline void RenderVoidActivation(TArray<int16>& Out) { RenderPcm16(Out, .24f, &VoidActivationSample); }
    inline void RenderVoidBurst(TArray<int16>& Out) { RenderPcm16(Out, .18f, &VoidBurstSample); }
    inline void RenderEntropyActivation(TArray<int16>& Out) { RenderPcm16(Out, EntropyActivationDurationSeconds, &EntropyActivationSample); }
    inline void RenderHitConfirm(TArray<int16>& Out) { RenderPcm16(Out, HitDurationSeconds, &HitConfirmSample); }
    inline void RenderKill(TArray<int16>& Out)       { RenderPcm16(Out, KillDurationSeconds, &KillSample); }
    inline void RenderTakeHit(TArray<int16>& Out)    { RenderPcm16(Out, TakeHitDurationSeconds, &TakeHitSample); }
    inline void RenderAbilityCast(TArray<int16>& Out) { RenderPcm16(Out, AbilityCastDurationSeconds, &AbilityCastSample); }
    inline void RenderPlayerDeath(TArray<int16>& Out) { RenderPcm16(Out, PlayerDeathDurationSeconds, &PlayerDeathSample); }

    // THE SEVENTH VERB: a level was gained (owner report: "could we add a
    // sound and a visual for leveling up"). The banner already existed and
    // was not felt; nothing in the game made a noise when the player grew.
    //
    // It is the only cue in this bank that RISES and the only one with no
    // noise term at all, which is the whole of how it is told apart: every
    // other verb here either falls (player death 110->55, entropy, the
    // reactions), carries grit, or sits under 200 Hz. Two STEPPED pure tones a
    // fourth apart rather than a glide, so it reads as a musical event instead
    // of a swoop — no other cue is stepped either. O179 files gold as reward,
    // and a level is a payment received.
    inline constexpr float LevelUpDurationSeconds = 0.55f;   // O2 PLACEHOLDER
    inline constexpr float LevelUpStepSeconds = 0.16f;       // O2 PLACEHOLDER
    inline float LevelUpSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const bool bSecond = T >= LevelUpStepSeconds;
        const float NoteT = bSecond ? T - LevelUpStepSeconds : T;
        const float NoteLength = bSecond ? LevelUpDurationSeconds - LevelUpStepSeconds : LevelUpStepSeconds;
        const float Hz = bSecond ? 880.0f : 587.33f;   // O2 PLACEHOLDER: A5 over D5.
        // The upper note carries a quiet octave so the top of the figure is
        // brighter than its start; the lower one is a plain tone.
        const float Body = FMath::Sin(2 * PI * Hz * NoteT)
            + (bSecond ? .25f * FMath::Sin(4 * PI * Hz * NoteT) : 0.0f);
        // The first note is clipped short by the step, so it decays fast; the
        // second rings out under the banner.
        return .34f * Body * Envelope(NoteT, NoteLength, bSecond ? 3.0f : 6.0f);   // O2 PLACEHOLDER
    }
    inline void RenderLevelUp(TArray<int16>& Out) { RenderPcm16(Out, LevelUpDurationSeconds, &LevelUpSample); }
}
