#pragma once

#include "CoreMinimal.h"

// ---------------------------------------------------------------------------
// The three placeholder sounds, SYNTHESIZED. Pure, header-inline, no world,
// no assets: every sample is a deterministic function of its index, which is
// what lets the automation suite prove the only things about a sound a test
// can prove — that it renders the length it claims, that no sample clips,
// that it starts and ends at silence (a waveform that begins off zero is an
// audible click), and that two renders are identical.
//
// WHY SYNTHESIS AND NOT A FILE. The project has no audio assets and the
// licensing of anything downloaded is the owner's problem and has to be
// visible. A sound generated by arithmetic in this header has no licence at
// all — the provenance IS the code. When real sounds arrive they replace the
// waves the director queues, and this header keeps rendering the fallback.
//
// Every figure below is O2 PLACEHOLDER: durations, frequencies, decay rates
// and gains are readability guesses that no playtest has confirmed.
// ---------------------------------------------------------------------------
namespace BreakerSound
{
    // 32 kHz mono: placeholder transients have no content above 10 kHz worth
    // keeping, and a smaller buffer is a cheaper queue. O2 PLACEHOLDER
    constexpr int32 SampleRate = 32000;

    constexpr float FireDurationSeconds = 0.14f;   // O2 PLACEHOLDER
    constexpr float HitDurationSeconds  = 0.06f;   // O2 PLACEHOLDER
    constexpr float KillDurationSeconds = 0.30f;   // O2 PLACEHOLDER

    inline int32 SampleCount(float DurationSeconds)
    {
        return FMath::Max(0, FMath::RoundToInt(DurationSeconds * SampleRate));
    }

    // Deterministic white noise: an integer hash of the sample index mapped to
    // [-1, 1]. NOT FMath::Rand — a seeded stream the caller cannot replay
    // would make the render nondeterministic and the determinism test above
    // is the whole point of doing this in a header.
    inline float NoiseAt(uint32 Index)
    {
        uint32 H = Index * 747796405u + 2891336453u;
        H = ((H >> ((H >> 28u) + 4u)) ^ H) * 277803737u;
        H = (H >> 22u) ^ H;
        return static_cast<float>(H) * (2.0f / 4294967295.0f) - 1.0f;
    }

    // Shared shape: a 2 ms attack ramp in and a hard fade over the final 10 ms
    // out, so no waveform ever starts or stops off zero. The decay between
    // them belongs to each sound.
    inline float Envelope(float T, float DurationSeconds, float DecayRate)
    {
        if (T < 0.0f || T >= DurationSeconds) return 0.0f;
        const float Attack = FMath::Min(T / 0.002f, 1.0f);
        const float Remaining = DurationSeconds - T;
        const float Release = FMath::Min(Remaining / 0.010f, 1.0f);
        return Attack * Release * FMath::Exp(-T * DecayRate);
    }

    // WEAPON FIRE: a noise burst over a falling body tone — the crack and the
    // thump of a report, in that order of weight. Gain 0.5 leaves headroom
    // for the hit and kill sounds to land on top of sustained fire.
    inline float WeaponFireSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Crack = NoiseAt(static_cast<uint32>(Index)) * Envelope(T, FireDurationSeconds, 55.0f);
        const float BodyHz = 160.0f - 400.0f * T;   // falls through the burst
        const float Body = FMath::Sin(2.0f * PI * BodyHz * T) * Envelope(T, FireDurationSeconds, 30.0f);
        return 0.5f * (0.65f * Crack + 0.35f * Body);
    }

    // HIT CONFIRM: a short bright tick, pitched well above the fire sound so
    // it reads THROUGH sustained fire rather than under it.
    inline float HitConfirmSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 1400.0f - 8000.0f * T;   // falls 1400 -> ~920 over 60 ms
        return 0.35f * FMath::Sin(2.0f * PI * Hz * T) * Envelope(T, HitDurationSeconds, 60.0f);
    }

    // KILL: a low two-tone drop, longer and heavier than either of the others
    // — the one event of the three that deserves weight.
    inline float KillSample(int32 Index)
    {
        const float T = static_cast<float>(Index) / SampleRate;
        const float Hz = 220.0f - 500.0f * T;   // falls 220 -> 70 over 300 ms
        const float Fundamental = FMath::Sin(2.0f * PI * Hz * T);
        const float Fifth = 0.4f * FMath::Sin(2.0f * PI * Hz * 1.5f * T);
        return 0.55f * (Fundamental + Fifth) / 1.4f * Envelope(T, KillDurationSeconds, 9.0f);
    }

    // Renders one whole sound as the 16-bit mono PCM the procedural wave
    // queues. The float sample is clamped before quantization so an authored
    // gain above 1 can distort but can never wrap.
    template <typename SampleFn>
    inline void RenderPcm16(TArray<int16>& Out, float DurationSeconds, SampleFn Sample)
    {
        const int32 Count = SampleCount(DurationSeconds);
        Out.SetNumUninitialized(Count);
        for (int32 Index = 0; Index < Count; ++Index)
        {
            const float Clamped = FMath::Clamp(Sample(Index), -1.0f, 1.0f);
            Out[Index] = static_cast<int16>(FMath::RoundToInt(Clamped * 32767.0f));
        }
    }

    inline void RenderWeaponFire(TArray<int16>& Out) { RenderPcm16(Out, FireDurationSeconds, &WeaponFireSample); }
    inline void RenderHitConfirm(TArray<int16>& Out) { RenderPcm16(Out, HitDurationSeconds, &HitConfirmSample); }
    inline void RenderKill(TArray<int16>& Out)       { RenderPcm16(Out, KillDurationSeconds, &KillSample); }
}
